export const CREATE_LETTER_SUCCESS = 'CREATE_LETTER_SUCCESS';
export const USE_LETTER_SUCCESS = 'USE_LETTER_SUCCESS';
export const USE_LETTER_FAIL = 'USE_LETTER_FAIL';
export const RESTORE_LETTER_SUCCESS = 'RESTORE_LETTER_SUCCESS';
export const ADD_LETTER_TO_WORD_SUCCESS = 'ADD_LETTER_TO_WORD_SUCCESS';
export const REMOVE_LETTER_FROM_WORD_SUCCESS = 'REMOVE_LETTER_FROM_WORD_SUCCESS';
export const CREATE_WORDS_SUCCESS = 'CREATE_WORD_SUCCESS';
