export const ADD_LETTER_SUCCESS = 'ADD_LETTER_SUCCESS';
export const UPDATE_LETTER_WORDID_SUCCESS = 'UPDATE_LETTER_WORDID_SUCCESS';
export const UPDATE_LETTER_GRIDID_SUCCESS = 'UPDATE_LETTER_GRIDID_SUCCESS';
